/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springworkspace;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
// import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Getter
@Setter
// @NoArgsConstructor // 각각 파라미터가 없는 생성자(빈 생성자) 자동 생성
@AllArgsConstructor // 모든 필드를 인자로 받는 생성자 자동 생성
@RequiredArgsConstructor // final 지정이 된 생성자 - 필수 필드만을 인자로 받는 생성자 자동 생성
@Builder // 빌더 디자인 패턴을 구현하는 코드를 자동으로 생성 - 복잡한 객체를 생성할 때 유용

class Person{

  private final String name;
  private int age;
}

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Person person = new Person("홍길동", 20); 
        person = new Person("고길동",20);

        person = Person.builder().name("홍길동").age(20).build();
    }
}
